apiVersion: apps/v1
kind: Deployment
metadata:
   name: rolling-update-deployment
   namespace: web-app
spec:
   replicas: 3
   selector:
      matchLabels:
          app: web-app
   template:
      metadata: 
         name: rolling-update-deployment
         labels: 
            app: web-app
      spec:
         containers:
             - name: webapp-deployment-container
               image: webapp:latest
               ports:
                 - containerPort: 3000
               volumeMounts:
                 - name: config-volume
                   mountPath: /etc/config
         volumes:
           - name: config-volume
             configMap:
                - name: web-app-deployment

  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1