#create a clusterIP- service file
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: web-app
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP #internal
